import type { Metadata } from 'next';
import '@/app/globals.css';
import { NavBar } from '@/components/navigationBar/navigationBar';
import { Toaster } from '@/components/ui/toaster';
import { auth } from '@/lib/auth';
import { redirect } from 'next/navigation';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  if (!session?.access_token) {
    redirect('/login');
  }
  console.log(session);
  return (
    <div>
      <NavBar />
      <div className="pt-24">{children}</div>
      <Toaster />
    </div>
  );
}
