/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Login user
     * @description Login user
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description user information */
      requestBody: {
        content: {
          'application/json': components['schemas']['dto.LoginRequestBody'];
        };
      };
      responses: {
        /** @description user successfully logged in */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.SuccessResponse-dto_TokenWithUserInformationResponseBody'];
          };
        };
        /** @description your request is invalid */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description your request is unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description user not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description system cannot login user */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Refresh user
     * @description Refresh user
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description user information */
      requestBody: {
        content: {
          'application/json': components['schemas']['dto.RefreshTokenRequestBody'];
        };
      };
      responses: {
        /** @description user successfully Refresh in */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.SuccessResponse-dto_TokenResponseBody'];
          };
        };
        /** @description your request is invalid */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description your request is unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description user not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description system cannot refresh user */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Register new user
     * @description Register new user
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description user information */
      requestBody: {
        content: {
          'application/json': components['schemas']['dto.RegisterRequestBody'];
        };
      };
      responses: {
        /** @description user successfully registered */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.SuccessResponse-dto_TokenWithUserInformationResponseBody'];
          };
        };
        /** @description your request is invalid */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description system cannot register user */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/dorms': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get all dorms by a search string
     * @description Retrieve a list of all dorms filtered by a search query. If no query is provided, all dorms are returned.
     */
    get: {
      parameters: {
        query?: {
          /** @description Search query */
          search?: string;
          /** @description Filter min price */
          minPrice?: number;
          /** @description Filter max price */
          maxPrice?: number;
          /** @description Filter district price */
          district?: string;
          /** @description Filter subdistrict price */
          subdistrict?: string;
          /** @description Filter province price */
          province?: string;
          /** @description Filter zipcode price */
          zipcode?: string;
          /** @description Number of dorms to retrieve (default 10, max 50) */
          limit?: number;
          /** @description Page number to retrieve (default 1) */
          page?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description All dorms retrieved successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.PaginationResponse-dto_DormResponseBody'];
          };
        };
        /** @description your request is unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description Failed to retrieve dorms */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    /**
     * Create a new dorm
     * @description Add a new room to the database with the given details
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description Dorm information */
      requestBody: {
        content: {
          'application/json': components['schemas']['dto.DormCreateRequestBody'];
        };
      };
      responses: {
        /** @description Dorm successfully created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.SuccessResponse-dto_DormResponseBody'];
          };
        };
        /** @description Your request is invalid */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description your request is unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description You do not have permission to create a dorm */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description Failed to save dorm */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/dorms/owner/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get dorms by owner ID
     * @description Retrieve all dorms of a specific owner ID
     */
    get: {
      parameters: {
        query?: {
          /** @description Number of dorms to retrieve (default 10, max 50) */
          limit?: number;
          /** @description Page number to retrieve (default 1) */
          page?: number;
        };
        header?: never;
        path: {
          /** @description OwnerID */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description All dorms retrieved successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.PaginationResponse-dto_DormResponseBody'];
          };
        };
        /** @description Incorrect UUID format */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description your request is unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description Failed to retrieve dorms */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/dorms/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a dorm by ID
     * @description Retrieve a specific dorm based on its ID
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description DormID */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Dorm data successfully retrieved */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.SuccessResponse-dto_DormResponseBody'];
          };
        };
        /** @description Incorrect UUID format */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description your request is unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description Dorm not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description Server failed to retrieve dorm */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    /**
     * Delete a dorm
     * @description Removes a dorm from the database based on the give ID
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description DormID */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Dorm successfully deleted */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Incorrect UUID format */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description your request is unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description You do not have permission to delete this dorm */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description Dorm not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description Failed to delete dorm */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    /**
     * Update an existing dorm
     * @description Modifies an existing room's details based on the given ID
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description DormID */
          id: string;
        };
        cookie?: never;
      };
      /** @description Updated Room Data */
      requestBody: {
        content: {
          'application/json': components['schemas']['dto.DormUpdateRequestBody'];
        };
      };
      responses: {
        /** @description Dorm data updated successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.SuccessResponse-dto_DormResponseBody'];
          };
        };
        /** @description Invalid Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description your request is unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description unauthorized to update this dorm */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description Dorm not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description Server failed to update dorm */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
      };
    };
    trace?: never;
  };
  '/dorms/{id}/images': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Upload an image for a dorm
     * @description Upload an image for a specific dorm by its ID, by attaching the image as a value for the key field name "image", as a multipart form-data
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description DormID */
          id: string;
        };
        cookie?: never;
      };
      /** @description DormImage */
      requestBody: {
        content: {
          'multipart/form-data': Record<string, never>;
        };
      };
      responses: {
        /** @description Successful image upload */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.SuccessResponse-dto_DormImageUploadResponseBody'];
          };
        };
        /** @description Invalid Request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description your request is unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description unauthorized to upload image to dorm */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description Dorm not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description Server failed to upload dorm image */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/history/bydorm/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get all leasing history by userid
     * @description Retrieve a list of all leasing history by userid
     */
    get: {
      parameters: {
        query?: {
          /** @description Number of dorms to retrieve (default 10, max 50) */
          limit?: number;
          /** @description Page number to retrieve (default 1) */
          page?: number;
        };
        header?: never;
        path: {
          /** @description DormID */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Retrive history successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.PaginationResponse-dto_LeasingHistory'];
          };
        };
        /** @description Incorrect UUID format or limit parameter is incorrect or page parameter is incorrect or page exceeded */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description your request is unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description leasing history not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description Can not parse UUID */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/history/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get all leasing history by userid
     * @description Retrieve a list of all leasing history by userid
     */
    get: {
      parameters: {
        query?: {
          /** @description Number of dorms to retrieve (default 10, max 50) */
          limit?: number;
          /** @description Page number to retrieve (default 1) */
          page?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Retrive history successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.PaginationResponse-dto_LeasingHistory'];
          };
        };
        /** @description Incorrect UUID format or limit parameter is incorrect or page parameter is incorrect or page exceeded */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description your request is unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description leasing history not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/history/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create a new leasing history
     * @description Add a new leasing history to the database
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description DormID */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Dorm successfully created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.SuccessResponse-dto_LeasingHistory'];
          };
        };
        /** @description Incorrect UUID format */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description your request is unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description Dorm not found or leasing history not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description Can not parse UUID or failed to save leasing history to database */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
      };
    };
    /**
     * Delete a leasing history
     * @description Delete a leasing history in the database
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description LeasingHistoryId */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description No Content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Incorrect UUID format */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description your request is unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description leasing history not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description Can not parse UUID or Failed to delete leasing history */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    /**
     * Delete a leasing history
     * @description Delete a leasing history in the database
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description LeasingHistoryId */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Set end timestamp successfully */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Incorrect UUID format */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description your request is unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description leasing history not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description Can not parse UUID or Failed to update leasing history */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
      };
    };
    trace?: never;
  };
  '/order': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create an order
     * @description Create an order
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description Order request body */
      requestBody: {
        content: {
          'application/json': components['schemas']['dto.OrderRequestBody'];
        };
      };
      responses: {
        /** @description Order created successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.SuccessResponse-dto_OrderResponseBody'];
          };
        };
        /** @description your request is invalid */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description your request is unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description leasing history not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description cannot parse uuid or cannot delete user */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/order/unpaid/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get my unpaid orders by ID
     * @description Get my unpaid orders by ID
     */
    get: {
      parameters: {
        query?: {
          /** @description Number of history to be retrieved */
          limit?: number;
          /** @description Page to retrieved */
          page?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Unpaid orders retrieved successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.PaginationResponse-dto_OrderResponseBody'];
          };
        };
        /** @description your request is invalid */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description your request is unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description leasing history not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description cannot parse uuid or cannot delete user */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/order/unpaid/{userID}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get unpaid orders by User ID
     * @description Get unpaid orders by User ID
     */
    get: {
      parameters: {
        query?: {
          /** @description Number of history to be retrieved */
          limit?: number;
          /** @description Page to retrieved */
          page?: number;
        };
        header?: never;
        path: {
          /** @description User ID */
          userID: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Order retrieved successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.PaginationResponse-dto_OrderResponseBody'];
          };
        };
        /** @description your request is invalid */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description your request is unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description leasing history not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description cannot parse uuid or cannot delete user */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/order/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get an order by ID
     * @description Get an order by ID
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description Order ID */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Order retrieved successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.SuccessResponse-dto_OrderResponseBody'];
          };
        };
        /** @description your request is invalid */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description your request is unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description leasing history not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description cannot parse uuid or cannot delete user */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ownership/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get ownership proof by Dorm ID
     * @description Retrieve ownership proof for a specific dorm
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description DormID */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Ownership proof retrieved successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.SuccessResponse-dto_OwnershipProofResponseBody'];
          };
        };
        /** @description Incorrect UUID format */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description Ownership file not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    /**
     * Delete ownership proof
     * @description Delete an ownership proof file
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description DormID */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Ownership proof successfully deleted */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Incorrect UUID format */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description Ownership file not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description Failed to delete Ownership file */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ownership/{id}/approve': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Approve ownership proof
     * @description Approve a submitted ownership proof for a dorm
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description DormID */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Ownership proof approved */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.SuccessResponse-dto_OwnershipProofResponseBody'];
          };
        };
        /** @description Incorrect UUID format */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description Ownership file not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ownership/{id}/reject': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reject ownership proof
     * @description Reject a submitted ownership proof for a dorm
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description DormID */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Ownership proof rejected */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.SuccessResponse-dto_OwnershipProofResponseBody'];
          };
        };
        /** @description Incorrect UUID format */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description Ownership file not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ownership/{id}/upload': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Upload new ownership proof
     * @description Upload a new file as ownership proof for a dorm
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description DormID */
          id: string;
        };
        cookie?: never;
      };
      /** @description file */
      requestBody: {
        content: {
          'multipart/form-data': Record<string, never>;
        };
      };
      responses: {
        /** @description Ownership proof created */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.SuccessResponse-dto_OwnershipProofResponseBody'];
          };
        };
        /** @description Incorrect UUID format */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description Ownershop proof not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description Server failed to upload file */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/transaction': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create a transaction
     * @description Create a transaction
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description Transaction request body */
      requestBody: {
        content: {
          'application/json': components['schemas']['dto.TransactionRequestBody'];
        };
      };
      responses: {
        /** @description Transaction created successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.SuccessResponse-dto_CreateTransactionResponseBody'];
          };
        };
        /** @description your request is invalid */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description your request is unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description leasing history not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description cannot parse uuid or cannot delete user */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/user': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update user information
     * @description Update user information
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description user information */
      requestBody: {
        content: {
          'application/json': components['schemas']['dto.UserInformationRequestBody'];
        };
      };
      responses: {
        /** @description user successfully updated account information */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.SuccessResponse-dto_UserResponse'];
          };
        };
        /** @description your request is invalid */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description your request is unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description system cannot update your account information */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
      };
    };
    trace?: never;
  };
  '/user/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete a user account
     * @description Delete a user account
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': Record<string, never>;
        };
      };
      responses: {
        /** @description account successfully deleted */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description your request is unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description cannot parse uuid or cannot delete user */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/user/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get user information
     * @description Get user information
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description get user information successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.SuccessResponse-dto_UserResponse'];
          };
        };
        /** @description your request is unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description system cannot get user information */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/user/newpassword': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reset password
     * @description Reset password
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description token */
      requestBody: {
        content: {
          'application/json': components['schemas']['dto.ResetPasswordRequestBody'];
        };
      };
      responses: {
        /** @description password reset successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.SuccessResponse-dto_TokenWithUserInformationResponseBody'];
          };
        };
        /** @description your request is invalid */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description system cannot reset password */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/user/resetpassword': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Resend verification email
     * @description Resend verification email
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description token */
      requestBody: {
        content: {
          'application/json': components['schemas']['dto.ResetPasswordCreateRequestBody'];
        };
      };
      responses: {
        /** @description email is sent to user successfully */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description your request is invalid */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description system cannot resend verification email */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/user/verify': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Verify email
     * @description Verify email
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description token */
      requestBody: {
        content: {
          'application/json': components['schemas']['dto.VerifyRequestBody'];
        };
      };
      responses: {
        /** @description email is verified successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.SuccessResponse-dto_TokenWithUserInformationResponseBody'];
          };
        };
        /** @description your request is invalid */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description your request is unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description system cannot verify your email */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/user/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * GetUserByID
     * @description Get User By ID
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          /** @description user id */
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description get user information successfully */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.SuccessResponse-dto_UserResponse'];
          };
        };
        /** @description your request is unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
        /** @description system cannot get user information */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['dto.ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    'dto.Address': {
      district?: string;
      province?: string;
      subdistrict?: string;
      zipcode?: string;
    };
    'dto.CreateTransactionResponseBody': {
      checkoutUrl?: string;
    };
    'dto.DormCreateRequestBody': {
      address: {
        district: string;
        province: string;
        subdistrict: string;
        zipcode: string;
      };
      bathrooms: number;
      bedrooms: number;
      description?: string;
      name: string;
      price: number;
      size: number;
    };
    'dto.DormImageUploadResponseBody': {
      url?: string;
    };
    'dto.DormResponseBody': {
      address?: components['schemas']['dto.Address'];
      bathrooms?: number;
      bedrooms?: number;
      createAt?: string;
      description?: string;
      id?: string;
      imagesUrl?: string[];
      name?: string;
      owner?: components['schemas']['dto.UserResponse'];
      price?: number;
      rating?: number;
      size?: number;
      updateAt?: string;
    };
    'dto.DormUpdateRequestBody': {
      address?: components['schemas']['dto.Address'];
      bathrooms?: number;
      bedrooms?: number;
      description?: string;
      name?: string;
      price?: number;
      size?: number;
    };
    'dto.ErrorResponse': {
      error?: string;
    };
    'dto.LeasingHistory': {
      dorm?: components['schemas']['dto.DormResponseBody'];
      end?: string;
      id?: string;
      lessee?: components['schemas']['dto.UserResponse'];
      orders?: components['schemas']['dto.OrderResponseBody'][];
      price?: number;
      start?: string;
    };
    'dto.LoginRequestBody': {
      email: string;
      password: string;
    };
    'dto.OrderRequestBody': {
      leasingHistoryId: string;
    };
    'dto.OrderResponseBody': {
      id?: string;
      paidTransaction?: components['schemas']['dto.TransactionResponse'];
      price?: number;
      type?: string;
    };
    'dto.OwnershipProofResponseBody': {
      adminId?: string;
      dormId?: string;
      status?: components['schemas']['dto.OwnershipProofStatus'];
      url?: string;
    };
    'dto.OwnershipProofStatus': string;
    'dto.Pagination': {
      current_page?: number;
      last_page?: number;
      limit?: number;
      total?: number;
    };
    'dto.PaginationResponse-dto_DormResponseBody': {
      data?: components['schemas']['dto.DormResponseBody'][];
      pagination?: components['schemas']['dto.Pagination'];
    };
    'dto.PaginationResponse-dto_LeasingHistory': {
      data?: components['schemas']['dto.LeasingHistory'][];
      pagination?: components['schemas']['dto.Pagination'];
    };
    'dto.PaginationResponse-dto_OrderResponseBody': {
      data?: components['schemas']['dto.OrderResponseBody'][];
      pagination?: components['schemas']['dto.Pagination'];
    };
    'dto.RefreshTokenRequestBody': {
      refreshToken: string;
    };
    'dto.RegisterRequestBody': {
      email: string;
      password: string;
      username: string;
    };
    'dto.ResetPasswordCreateRequestBody': {
      email: string;
    };
    'dto.ResetPasswordRequestBody': {
      password: string;
      token: string;
    };
    'dto.SuccessResponse-dto_CreateTransactionResponseBody': {
      data?: components['schemas']['dto.CreateTransactionResponseBody'];
    };
    'dto.SuccessResponse-dto_DormImageUploadResponseBody': {
      data?: components['schemas']['dto.DormImageUploadResponseBody'];
    };
    'dto.SuccessResponse-dto_DormResponseBody': {
      data?: components['schemas']['dto.DormResponseBody'];
    };
    'dto.SuccessResponse-dto_LeasingHistory': {
      data?: components['schemas']['dto.LeasingHistory'];
    };
    'dto.SuccessResponse-dto_OrderResponseBody': {
      data?: components['schemas']['dto.OrderResponseBody'];
    };
    'dto.SuccessResponse-dto_OwnershipProofResponseBody': {
      data?: components['schemas']['dto.OwnershipProofResponseBody'];
    };
    'dto.SuccessResponse-dto_TokenResponseBody': {
      data?: components['schemas']['dto.TokenResponseBody'];
    };
    'dto.SuccessResponse-dto_TokenWithUserInformationResponseBody': {
      data?: components['schemas']['dto.TokenWithUserInformationResponseBody'];
    };
    'dto.SuccessResponse-dto_UserResponse': {
      data?: components['schemas']['dto.UserResponse'];
    };
    'dto.TokenResponseBody': {
      accessToken?: string;
      refreshToken?: string;
    };
    'dto.TokenWithUserInformationResponseBody': {
      accessToken?: string;
      refreshToken?: string;
      userInformation?: components['schemas']['dto.UserResponse'];
    };
    'dto.TransactionRequestBody': {
      orderID?: string;
    };
    'dto.TransactionResponse': {
      createAt?: string;
      id?: string;
      price?: number;
      status?: string;
      updateAt?: string;
    };
    'dto.UserInformationRequestBody': {
      birthDate?: string;
      firstname?: string;
      gender?: string;
      lastname?: string;
      lifestyles?: string[];
      nationalID?: string;
      password?: string;
      phoneNumber?: string;
      studentEvidence?: string;
      username?: string;
    };
    'dto.UserResponse': {
      birthDate?: string;
      email?: string;
      filledPersonalInfo?: boolean;
      firstname?: string;
      gender?: string;
      id?: string;
      isStudentVerified?: boolean;
      isVerified?: boolean;
      lastname?: string;
      lifestyles?: string[];
      phoneNumber?: string;
      role?: string;
      studentEvidence?: string;
      username?: string;
    };
    'dto.VerifyRequestBody': {
      token: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
