import { Property } from '../../types/property';

const mockArray = [
  new Property(
    1,
    '/image.jpeg',
    4.9,
    2,
    1,
    'Bangkok',
    'Pathumwan',
    12000,
    'IdeoQ Chula',
    'PitiOwner',
    34.5,
    'This is condo opposite of Samyam Mitrtown'
  ),
  new Property(
    2,
    '/image.jpeg',
    4.9,
    2,
    1,
    'Bangkok',
    'Pathumwan',
    12000,
    'IdeoQ Chula',
    'PitiOwner',
    34.5,
    'This is condo opposite of Samyam Mitrtown'
  ),
  new Property(
    3,
    '/image.jpeg',
    4.9,
    2,
    1,
    'Bangkok',
    'Pathumwan',
    12000,
    'IdeoQ Chula',
    'PitiOwner',
    34.5,
    'This is condo opposite of Samyam Mitrtown'
  ),
  new Property(
    4,
    '/image.jpeg',
    4.9,
    2,
    1,
    'Bangkok',
    'Pathumwan',
    12000,
    'IdeoQ Chula',
    'PitiOwner',
    34.5,
    'This is condo opposite of Samyam Mitrtown'
  ),
  new Property(
    5,
    '/image.jpeg',
    4.9,
    2,
    1,
    'Bangkok',
    'Pathumwan',
    12000,
    'IdeoQ Chula',
    'PitiOwner',
    34.5,
    'This is condo opposite of Samyam Mitrtown'
  ),
  new Property(
    6,
    '/image.jpeg',
    4.9,
    2,
    1,
    'Bangkok',
    'Pathumwan',
    12000,
    'IdeoQ Chula',
    'PitiOwner',
    34.5,
    'This is condo opposite of Samyam Mitrtown'
  ),
  new Property(
    7,
    '/image.jpeg',
    4.9,
    2,
    1,
    'Bangkok',
    'Pathumwan',
    12000,
    'IdeoQ Chula',
    'PitiOwner',
    34.5,
    'This is condo opposite of Samyam Mitrtown'
  ),
  new Property(
    8,
    '/image.jpeg',
    4.9,
    2,
    1,
    'Bangkok',
    'Pathumwan',
    12000,
    'IdeoQ Chula',
    'PitiOwner',
    34.5,
    'This is condo opposite of Samyam Mitrtown'
  ),
  new Property(
    9,
    '/image.jpeg',
    4.9,
    2,
    1,
    'Bangkok',
    'Pathumwan',
    12000,
    'IdeoQ Chula',
    'PitiOwner',
    34.5,
    'This is condo opposite of Samyam Mitrtown'
  ),
  new Property(
    11,
    '/image.jpeg',
    4.9,
    2,
    1,
    'Bangkok',
    'Pathumwan',
    12000,
    'IdeoQ Chula',
    'PitiOwner',
    34.5,
    'This is condo opposite of Samyam Mitrtown'
  ),
  new Property(
    10,
    '/image.jpeg',
    4.9,
    2,
    1,
    'Bangkok',
    'Pathumwan',
    12000,
    'IdeoQ Chula',
    'PitiOwner',
    34.5,
    'This is condo opposite of Samyam Mitrtown'
  ),
  new Property(
    12,
    '/image.jpeg',
    4.9,
    2,
    1,
    'Bangkok',
    'Pathumwan',
    12000,
    'IdeoQ Chula',
    'PitiOwner',
    34.5,
    'This is condo opposite of Samyam Mitrtown'
  ),
  new Property(
    13,
    '/image.jpeg',
    4.9,
    2,
    1,
    'Bangkok',
    'Pathumwan',
    12000,
    'IdeoQ Chula',
    'PitiOwner',
    34.5,
    'This is condo opposite of Samyam Mitrtown'
  ),
  new Property(
    14,
    '/image.jpeg',
    4.9,
    2,
    1,
    'Bangkok',
    'Pathumwan',
    12000,
    'IdeoQ Chula',
    'PitiOwner',
    34.5,
    'This is condo opposite of Samyam Mitrtown'
  ),
];

export const mockData = JSON.stringify(mockArray);
